### ISSUE TITLE
system/lib/hw/sensors.montblanc.so is missing in the latest sourcetree

### ISSUE THREAD

**Issue by HFriebis** [J-Team/J-Team#1]
in the latest source the sensors.montblanc.so is missing with the consequence  the gps is not working.
below my changes:

```
$(LOCAL_PATH)/system/etc/param.dat:system/etc/param.dat \
$(LOCAL_PATH)/system/etc/sensors.dat:system/etc/sensors.dat \
  $(LOCAL_PATH)/system/lib/hw/sensors.montblanc.so:system/lib/hw/sensors.montblanc.so
```

**Comment by davidepianca98** [comment]
It is there but it has been commented because we were building it from source. Then we forgot to enable it again. Thanks for reminding
