### ISSUE TITLE
wifi issue

### ISSUE THREAD

**Issue by HFriebis** [J-Team/J-Team#2]
I have the replaced the drivers from Broadcom  by the TeamCanjica (https://github.com/TeamCanjica/Samsung_STE_Kernel-b 3.0.31). 
After this update the wifi works as expected.

Best Regards

Hermann

**Comment by Chirag-Galani** [comment]
So using this kernel instead of android_kernel_u8500 will fix the issue ?

**Comment by HFriebis** [comment]
yes, using this  kernel solve the wifi problem. But this kernel has a problem with the compass.
Therefore I copied only the broadcom software (drivers/mmc and  drivers/net/wireless).

And the compass an wifi is working

**Comment by Chirag-Galani** [comment]
Where have u copied ?
Repo link and which branch of kernel 3.0.31 or 3.0.101 ?

**Comment by HFriebis** [comment]
The repo link:
git clone https://github.com/TeamCanjica/android_kernel_samsung_u8500 -b cm-11.0
1. cd android_kernel_samsung_u8500
2. cp -r drivers/mmc ~/android/aosp/kernel/samsung/u8500/drivers
3. cp -r drivers/net/wireless /android/aosp/kernel/samsung/u8500/drivers/net

That all.

**Comment by HFriebis** [comment]
sorry the branch is wrong. the branch is 3.0.31

**Comment by Chirag-Galani** [comment]
Then what about https://github.com/TeamCanjica/Samsung_STE_Kernel
