### ISSUE TITLE
wifi issue

### ISSUE THREAD

**Issue by HFriebis** [J-Team/J-Team#3]
do fix the wifi bug you should use the kernel from Team Canjica:

project path="kernel/samsung/u8500" name="TeamCanjica/Samsung_STE_Kernel" revision="3.0.31"
or
 git clone https://github.com/Novathor/Samsung_STE_Kernel -b 3.0.31

**Comment by Chirag-Galani** [comment]
1st one is preferred over cloning repo. :)

**Comment by Alberto97** [comment]
Thank you :)
